version: '3'

volumes:
  vol_mysql57:
  vol_mysql80:
networks:
  devbox:

services:
  caddy:
    image: caddy/caddy
    ports:
      - 127.0.0.1:80:80
      - 127.0.0.1:443:443
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/Caddysites:/etc/caddy/Caddysites
      - ./www:/www
    networks:
      - devbox
  phpfpm:
    image: devbox/phpfpm-alpine:dev
    build:
      context: ./phpfpm
      dockerfile: Dockerfile.alpine-dev
      args:
        USER_ID: 1000
        GROUP_ID: 1000
    networks:
      - devbox
    volumes:
      - ./www:/www
  phpfpm_xdebug:
    image: devbox/phpfpm-alpine:xdebug
    build:
      context: ./phpfpm
      dockerfile: Dockerfile.alpine-xdebug
      args:
        USER_ID: 1000
        GROUP_ID: 1000
    networks:
      - devbox
    volumes:
      - ./www:/www
  redis:
    image: redis:5-alpine
    ports:
      - 127.0.0.1:6379:6379
    networks:
      - devbox
  # mysql57:
  #   image: mysql:5.7
  #   ports:
  #     - 5706:3306
  #   networks:
  #     - devbox
  #   environment:
  #     MYSQL_ROOT_PASSWORD: passwd
  #   volumes:
  #     - vol_mysql57:/var/lib/mysql
  mysql80:
    image: mysql:8.0
    ports:
      - 127.0.0.1:8006:3306
    networks:
      - devbox
    environment:
      MYSQL_ROOT_PASSWORD: passwd
    volumes:
      - vol_mysql80:/var/lib/mysql
  mailhog:
    image: mailhog/mailhog
    ports:
      - 127.0.0.1:1025:1025
      - 127.0.0.1:8025:8025
    networks:
      - devbox
      
