FROM php:7.4-fpm-alpine

RUN apk add --no-cache libzip-dev freetype libpng libjpeg-turbo freetype-dev libpng-dev libjpeg-turbo-dev postgresql-dev && \
    docker-php-ext-configure gd --with-freetype=/usr/include/ --with-jpeg=/usr/include/ && \
    docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql && \
    docker-php-ext-install gd zip pdo_mysql pdo_pgsql && \
    apk add --no-cache $PHPIZE_DEPS && \
    yes 'no' | pecl install redis && \
    docker-php-ext-enable redis && \
    rm -rf /var/cache/apk/* && \
    rm -rf /tmp/*

RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" && \
    php -r "if (hash_file('sha384', 'composer-setup.php') === 'e0012edf3e80b6978849f5eff0d4b4e4c79ff1609dd1e613307e16318854d24ae64f26d17af3ef0bf7cfb710ca74755a') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;" && \
    php composer-setup.php && \
    php -r "unlink('composer-setup.php');" && \
    mv composer.phar /usr/local/bin/composer

COPY ./www.conf /usr/local/etc/php-fpm.d/www.conf
COPY ./devbox.ini /usr/local/etc/php/conf.d/devbox.ini

ARG USER_ID
ARG GROUP_ID

RUN addgroup -g $GROUP_ID phpfpm
RUN adduser -D -g '' -u $USER_ID -G phpfpm phpfpm
USER phpfpm

RUN composer global require -vvv --prefer-dist hirak/prestissimo && rm -rf /home/phpfpm/.composer/cache

CMD ["php-fpm"]
